server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.92.194.175:3306/jeecg-boot?useUnicode=true&useSSL=false&characterEncoding=utf8&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: SH-Dhls@2020.com
  activiti:
    check-process-definitions: false