server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://49.235.101.88:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root@123
  activiti:
    check-process-definitions: false